### ISSUE TITLE
Scenario 12 Progression Tracker

### ISSUE THREAD

**Issue by knyghtmare** [nemaara/Northern_Rebirth_Reborn#16]
# The Progression Tracker

## Maps:

- [x] Floor 1
- [x] Floor 2
- [ ] Floor 3
- [x] Floor 4

## Map Refinements (Runes/Terrain Code Variety/embellishments)

- [ ] Floor 1
- [ ] Floor 2
- [ ] Floor 3
- [ ] Floor 4

## Code

- [ ] Floor 1 Part 1 Events
- [ ] Floor 2 Events
- [ ] Floor 3 Events
- [ ] Floor 4 Events Part X
    - [ ] Floor 4 X Part A
    - [ ] Floor 4 X Part B
- [ ] Floor 4 Events Part Y
    - [ ] Floor 4 Y Part C
    - [ ] Floor 4 Y Part D
- [ ] Final Descent Events

- [ ] Runic Events
    - [ ] Heal Runes
    - [ ] Harm Runes Fire
    - [ ] Harm Runes Cold
    - [ ] Speed Runes
    - [ ] Gate Runes
    - [ ] Death Runes
